export const FETCH_TASKS_SUCCEEDED = "FETCH_TASKS_SUCCEEDED";
export const FETCH_TASKS_STARTED = "FETCH_TASKS_STARTED";
export const FETCH_TASKS_FAILED = "FETCH_TASKS_FAILED";
export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_STARTED = "CREATE_TASK_STARTED";
export const CREATE_TASK_SUCCEEDED = "CREATE_TASK_SUCCEEDED";
export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_SUCCEEDED = "EDIT_TASK_SUCCEEDED";
